# Generated by Django 5.1.7 on 2025-04-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroAlunos",
            fields=[
                (
                    "ra",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nome_estudante", models.CharField(max_length=255)),
                ("serie_turma", models.CharField(max_length=5)),
                ("endereco", models.CharField(max_length=255)),
                ("responsavel1", models.CharField(max_length=255)),
                (
                    "responsavel2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contato", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RegAtrasos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_atraso", models.DateField()),
                ("horario_chegada", models.TimeField()),
                ("justificativa", models.TextField(max_length=255)),
                (
                    "ra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_gestao.cadastroalunos",
                    ),
                ),
            ],
        ),
    ]
