# Generated by Django 5.1.7 on 2025-05-11 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_gestao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastroalunos",
            name="ra",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("presente", models.BooleanField(default=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_gestao.cadastroalunos",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "data")},
            },
        ),
    ]
